<a href="https://colab.research.google.com/github/MGSev/Shortcut-Learning/blob/main/Experiment_Features_collapsed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
from torch import sigmoid





In [29]:
from pandas.io.api import read_csv

print("="*50)
print("Dataset Analysis")
print("="*50)


# Import the Dataset
df = pd.read_excel('cow_dataset3.xlsx')
print("Dataset:")
print(df.to_string(index=False))


# Extract features and labels
X = df[['Grass_Background', 'Shape', 'Colour']].values
y = df['Label'].values
print("\nDataset (first 5 rows):")
print(df.head().to_string(index=False))
print(f"Total samples: {len(y)}")
print(f"Cows (label=1): {sum(y==1)}")
print(f"Non-Cows (label=0): {len(y) - sum(y)}")
print(f"\nLabels y: {y}")


#Convert to tensor
X_tensor = torch.tensor(df[['Grass_Background', 'Shape', 'Colour']].values, dtype=torch.float32)
y_tensor = torch.tensor(df['Label'].values, dtype=torch.float32).reshape(-1, 1)
print(f"nX_tensor shape: {X_tensor.shape}")
print(f"y_tensor shape: {y_tensor.shape}")

print(f"\nFirst three rows of X_tensor")
print(X_tensor[:3])
print(f"\nFirst three rows of y_tensor")
print(y_tensor[:3])

Dataset Analysis
Dataset:
 Grass_Background  Shape  Colour  Label
                1      1       1      1
                1      1       1      1
                1      1       0      1
                1      1       1      1
                1      1       1      1
                1      0       1      1
                1      1       1      1
                1      1       0      1
                1      1       1      1
                1      1       1      1
                1      1       1      1
                1      0       1      1
                1      1       1      1
                1      1       0      1
                1      1       1      1
                1      1       1      1
                1      0       1      1
                1      1       1      1
                1      1       0      1
                1      1       1      1
                1      0       1      1
                0      0       0      0
                0      0       0      0
              

In [30]:
## creating a class for simple FF-NN (three input layers, 10 hidden layer, one output layer)

class Net(nn.Module):
    def __init__(self, N_in, N_h, N_out):
        super(Net, self).__init__()
        self.linear1 = nn.Linear(N_in, N_h)
        self.linear2 = nn.Linear(N_h, N_out)
    def forward(self, x):
        oh = sigmoid(self.linear1(x))
        oo = sigmoid(self.linear2(oh))
        return oo


In [31]:
# Creating a network with three input neuron, 10 hidden neurons, one output neuron
my_network = Net(3, 10, 1)
print(my_network)

# parameters can be seen in different ways

print(list(my_network.parameters()))

for p in list(my_network.parameters()):
    print(p)

my_network.state_dict()

for p, v in my_network.state_dict().items():
    print(p, v)

Net(
  (linear1): Linear(in_features=3, out_features=10, bias=True)
  (linear2): Linear(in_features=10, out_features=1, bias=True)
)
[Parameter containing:
tensor([[ 0.0843,  0.2461, -0.2438],
        [ 0.5687,  0.0199, -0.0105],
        [ 0.1363, -0.4904, -0.3953],
        [ 0.4434, -0.0077,  0.1028],
        [ 0.3532, -0.3251,  0.3802],
        [ 0.1921,  0.4878,  0.5168],
        [ 0.4530, -0.5184,  0.2244],
        [ 0.4614,  0.3997, -0.5508],
        [-0.1234,  0.1312,  0.4072],
        [ 0.5307,  0.0087, -0.3170]], requires_grad=True), Parameter containing:
tensor([-0.2441,  0.2409, -0.3287,  0.2441,  0.4344,  0.3114, -0.3702,  0.1350,
        -0.5571,  0.0139], requires_grad=True), Parameter containing:
tensor([[-0.2785, -0.3061,  0.0202,  0.1465, -0.0945, -0.1667,  0.2812, -0.1464,
          0.1359,  0.0258]], requires_grad=True), Parameter containing:
tensor([0.0009], requires_grad=True)]
Parameter containing:
tensor([[ 0.0843,  0.2461, -0.2438],
        [ 0.5687,  0.0199, -0.

In [32]:
# Creating input
x1 = X_tensor
print(x1)
# Creating output of the network (forward pass)
y1 = my_network(x1)
print(y1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 0.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 0., 1.],
        [1., 1., 1.],
        [1., 1., 0.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 0., 1.],
        [1., 1., 1.],
        [1., 1., 0.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 0., 1.],
        [1., 1., 1.],
        [1., 1., 0.],
        [1., 1., 1.],
        [1., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 0.]])
tensor([[0.4200],
        [0.4200],
        [0.4101],
        [0.4200],
        [0.4200],
        [0.4383],
        [0.4200],
        [0.4101],
        [0.4200],
        [0.4200],
        [0.4200],
        [0.4383],
        [0.4200],
        [0.4101],
        [0.4200],
        [0.4200],
        [0.4383],
        [0.4200],
        [0.4101

In [33]:
# Loss function

error = nn.MSELoss()

y_compare = y_tensor
loss = error(y1, y_compare)
print(loss)
print(y_compare)
print(f"Loss: {loss.item()}")

tensor(0.2908, grad_fn=<MseLossBackward0>)
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
Loss: 0.2908012568950653


In [34]:
# Forward pass
y1 = my_network(x1)

# Calculate loss
loss = error(y1, y_compare)

# Backward pass
loss.backward()

In [35]:
# Weights Update

learning_rate = 0.07
for f in my_network.parameters():
    f.data.sub_(f.grad.data * learning_rate)

In [36]:
#Checking the loss
y1_new = my_network(x1)
loss_new = error(y1, y_compare)

print(f"Lossafter the firts update: {loss_new.item()}")

Lossafter the firts update: 0.2908012568950653


In [49]:
#Training the loop
my_network.zero_grad()
for epoch in range(9000):
  y_prediction = my_network(x1)
  loss = error(y_prediction, y_compare)
  my_network.zero_grad()
  loss.backward()
  for p in my_network.parameters():
    p.data = p.data - p.grad.data * learning_rate
  if epoch % 1000 == 0:
      print(f"Epoch: {epoch}, Loss: {loss.item():.6f}")


print(f"Loss after training: {loss.item():.6f}")

Epoch: 0, Loss: 0.000636
Epoch: 1000, Loss: 0.000582
Epoch: 2000, Loss: 0.000536
Epoch: 3000, Loss: 0.000496
Epoch: 4000, Loss: 0.000462
Epoch: 5000, Loss: 0.000431
Epoch: 6000, Loss: 0.000405
Epoch: 7000, Loss: 0.000381
Epoch: 8000, Loss: 0.000359
Loss after training: 0.000340


In [50]:
with torch.no_grad():
  H = sigmoid(my_network.linear1(X_tensor)).numpy()


rank_input = np.linalg.matrix_rank(X_tensor.numpy())
rank_hidden = np.linalg.matrix_rank(H)

print("="*50)
print("Feature Collapse Analysis")
print("="*50)
print(f"\nInput tensor X_tensor shape: {X_tensor.shape}")
print(f"Hidden activations H shape: {H.shape}")
print(f"\nRank  of Input: {rank_input}")
print(f"Rank  of Hidden Layer: {rank_hidden} (Hidden Layer max = 10)")


if rank_hidden < 10:
  print(f"Feature Collapse Detected: from 10 to {rank_hidden}")
print(f"Shape and colour, although causally relevant, were discarded")

Feature Collapse Analysis

Input tensor X_tensor shape: torch.Size([30, 3])
Hidden activations H shape: (30, 10)

Rank  of Input: 3
Rank  of Hidden Layer: 6 (Hidden Layer max = 10)
Feature Collapse Detected: from 10 to 6
Shape and colour, although causally relevant, were discarded


In [53]:
# Counterfactual test
print("="*50)
print("Counterfactual Test")
print("="*50)
print("Input: grass=0, shape=1, colour=1")
print("(no grass, but shape and colour both say 'cow')")

counterfactual = torch.tensor([[0.0, 1.0, 1.0]])
with torch.no_grad():
    pred_cf = my_network(counterfactual)
print(f"\nPrediction = {pred_cf.item():.3f}")
print("Close to 0 = shortcut learned. Close to 1 = causal features learned.")


Counterfactual Test
Input: grass=0, shape=1, colour=1
(no grass, but shape and colour both say 'cow')

Prediction = 0.109
Close to 0 = shortcut learned. Close to 1 = causal features learned.


AI contribution disclosure: The framework was refined with guidance from Claude (Anthropic), used as a study assistant. The counterfactual test was proposed by the AI system. Data design, network development, and final evaluation were conducted independently.