<a href="https://colab.research.google.com/github/MGSev/Shortcut-Learning/blob/main/FEATURES_COLLAPSED.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Synthetic dataset to test feature collapse: 30 samples and 3 features (grass background, shape, colour). Grass perfectly predicts the cow label, intentionally introducing a shortcut.
---



In [ ]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
from torch import sigmoid






In [ ]:
from pandas.io.api import read_csv

print("="*50)
print("Dataset Analysis")
print("="*50)


# Import the Dataset
df = pd.read_excel('cow_dataset2.xlsx')
print("Dataset:")
print(df.to_string(index=False))


# Extract features and labels
X = df[['Grass_Background', 'Shape', 'Colour']].values
y = df['Label'].values
print("\nDataset (first 5 rows):")
print(df.head().to_string(index=False))
print(f"Total samples: {len(y)}")
print(f"Cows (label=1): {sum(y==1)}")
print(f"Non-Cows (label=0): {len(y) - sum(y)}")
print(f"\nLabels y: {y}")


#Convert to tensor
X_tensor = torch.tensor(df[['Grass_Background', 'Shape', 'Colour']].values, dtype=torch.float32)
y_tensor = torch.tensor(df['Label'].values, dtype=torch.float32).reshape(-1, 1)
print(f"nX_tensor shape: {X_tensor.shape}")
print(f"y_tensor shape: {y_tensor.shape}")

print(f"\nFirst three rows of X_tensor")
print(X_tensor[:3])
print(f"\nFirst three rows of y_tensor")
print(y_tensor[:3])



Dataset Analysis
Dataset:
 Grass_Background  Shape  Colour  Label
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                1 0.0001  0.0001      1
                0 0.0001  0.0001      0
                0 0.0001  0.0001      0
              

Creating a class (three input layers, 10 hidden layer, one output layer)




In [ ]:
## creating a class for simple FF-NN (three input layers, 10 hidden layer, one output layer)

class Net(nn.Module):
    def __init__(self, N_in, N_h, N_out):
        super(Net, self).__init__()
        self.linear1 = nn.Linear(N_in, N_h)
        self.linear2 = nn.Linear(N_h, N_out)
    def forward(self, x):
        oh = sigmoid(self.linear1(x))
        oo = sigmoid(self.linear2(oh))
        return oo




Creating actual network with three input neuron, ten hidden neurons, one output neuron


In [ ]:
# Creating a network with three input neuron, 10 hidden neurons, one output neuron
my_network = Net(3, 10, 1)
print(my_network)

# parameters can be seen in different ways

print(list(my_network.parameters()))

for p in list(my_network.parameters()):
    print(p)

my_network.state_dict()

for p, v in my_network.state_dict().items():
    print(p, v)

Net(
  (linear1): Linear(in_features=3, out_features=10, bias=True)
  (linear2): Linear(in_features=10, out_features=1, bias=True)
)
[Parameter containing:
tensor([[-0.1890,  0.0283, -0.3875],
        [-0.0459, -0.5614, -0.1223],
        [ 0.2285, -0.5127, -0.5102],
        [ 0.4517,  0.5134,  0.5485],
        [-0.4305,  0.1592,  0.1502],
        [ 0.4642, -0.4116, -0.2505],
        [ 0.0656,  0.4793, -0.0098],
        [-0.3084,  0.0461, -0.4534],
        [ 0.0173, -0.0459,  0.1870],
        [ 0.2099,  0.5722, -0.4100]], requires_grad=True), Parameter containing:
tensor([ 0.0434, -0.4213,  0.0818,  0.0901, -0.4994,  0.3828, -0.4254, -0.0598,
        -0.4594,  0.3708], requires_grad=True), Parameter containing:
tensor([[-0.2706,  0.0410, -0.1903, -0.1605, -0.1892, -0.2263,  0.0507, -0.1537,
          0.3048,  0.0057]], requires_grad=True), Parameter containing:
tensor([0.0722], requires_grad=True)]
Parameter containing:
tensor([[-0.1890,  0.0283, -0.3875],
        [-0.0459, -0.5614, -0.

Creating input and output of the network forward pass

In [ ]:
# Creating input
x1 = X_tensor
print(x1)
# Creating output of the network (forward pass)
y1 = my_network(x1)
print(y1)

tensor([[1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [0.0000e+00, 1.0000e-04, 1

Loss Function

In [ ]:
# Loss function

error = nn.MSELoss()

y_compare = y_tensor
loss = error(y1, y_compare)
print(loss)
print(y_compare)
print(f"Loss: {loss.item()}")

tensor(0.2968, grad_fn=<MseLossBackward0>)
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
Loss: 0.2967974543571472


Forward and Backward Pass

In [ ]:
# Forward pass
y1 = my_network(x1)

# Calculate loss
loss = error(y1, y_compare)

# Backward pass
loss.backward()

Weights Update

In [ ]:
# Weights Update

learning_rate = 0.07
for f in my_network.parameters():
    f.data.sub_(f.grad.data * learning_rate)

Checking the loss after the first update

In [ ]:
#Checking the loss
y1_new = my_network(x1)
loss_new = error(y1, y_compare)

print(f"Lossafter the firts update: {loss_new.item()}")

Lossafter the firts update: 0.2967974543571472



Training the loop


In [ ]:
#Training the loop
my_network.zero_grad()
for epoch in range(2000):
  y_prediction = my_network(x1)
  loss = error(y_prediction, y_compare)
  my_network.zero_grad()
  loss.backward()
  for p in my_network.parameters():
    p.data = p.data - p.grad.data * learning_rate
  if epoch % 1000 == 0:
      print(f"Epoch: {epoch}, Loss: {loss.item():.6f}")


print(f"Loss after training: {loss.item():.6f}")

Epoch: 0, Loss: 0.023727
Epoch: 1000, Loss: 0.008222
Loss after training: 0.004424


Feature Collapse`. After training a shallow network (one hidden layer and 10 neurons) I evaluated the rank of the hidden activations. A high rank suggests the use of many independent features, while low rank (collapsed) reflects the network's reliance on few features. The rank collapsed from 10 to 2, indicating the model used grass as a shortcut and discarded shape and colour features.



In [ ]:
with torch.no_grad():
  H = sigmoid(my_network.linear1(X_tensor)).numpy()


rank_input = np.linalg.matrix_rank(X_tensor.numpy())
rank_hidden = np.linalg.matrix_rank(H)

print("="*50)
print("Feature Collapse Analysis")
print("="*50)
print(f"\nInput tensor X_tensor shape: {X_tensor.shape}")
print(f"Hidden activations H shape: {H.shape}")
print(f"\nRank  of Input: {rank_input}")
print(f"Rank  of Hidden Layer: {rank_hidden} (Hidden Layer max = 10)")


if rank_hidden < 10:
  print(f"Feature Collapse Detected: from 10 to {rank_hidden}")
print(f"The network only learned the feature shortcut (Grass_Background)")

Feature Collapse Analysis

Input tensor X_tensor shape: torch.Size([30, 3])
Hidden activations H shape: (30, 10)

Rank  of Input: 2
Rank  of Hidden Layer: 2 (Hidden Layer max = 10)
Feature Collapse Detected: from 10 to 2
The network only learned the feature shortcut (Grass_Background)
